### ISSUE TITLE
Feature: support parsing of nested groups

### ISSUE THREAD

**Issue by blaise-sumo** [multigcs/visansible#1]
Hi @multigcs , this was reported on the Ansible mailing list and I thought it might help to log it here.

> Just to say that the issue I had turned out to be because the parsing doesn't handle the possibility that an inventory group may contain the name of one or more groups. Simple fix seems to be to ignore the line in this case and not to support visualisation of groups within groups, for now.

```
Traceback (most recent call last):
  File "visansible.py", line 1663, in <module>
    inventory_read()
  File "visansible.py", line 1604, in inventory_read
    value = line.split("=")[1].strip()
IndexError: list index out of range
```

**Comment by multigcs** [comment]
Hi blaise-sumo,
thank you for the bug-report, hope this will fix the issue:

https://github.com/multigcs/visansible/commit/c91d0734cf4f3da5c136170770a5dc37f25f89d1
